const CONFIG={business:"Fisioterapia 5",address:"La ubicación se confirma directamente con Fisioterapia 5.",mapUrl:"",bank:"Solicita a Fisioterapia 5 la cuenta y referencia vigentes antes de realizar tu transferencia.",storage:"fisio5Appointments"};
const SERVICES=[
{id:"first_time",area:"valuation",name:"Primera vez",minutes:60,price:0},
{id:"followup",area:"followup",name:"Seguimiento",minutes:60,price:0},
{id:"geriatric",area:"valuation_treatment",name:"Geriátrica",minutes:60,price:0},
{id:"sports",area:"valuation_treatment",name:"Deportiva",minutes:60,price:0},
{id:"neurological",area:"valuation_treatment",name:"Neurológico",minutes:60,price:0},
{id:"home",area:"valuation_treatment",name:"A domicilio",minutes:60,price:0},
{id:"discharge",area:"valuation_treatment",name:"Descarga",minutes:60,price:0}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={services:[],date:null,time:null,month:new Date(new Date().getFullYear(),new Date().getMonth(),1)};
const views={home:$("#inicio"),booking:$("#bookingView"),confirmation:$("#confirmationView"),admin:$("#adminView"),agenda:$("#agendaView")};
const pad=n=>String(n).padStart(2,"0");
const toISO=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const fromISO=s=>{const [y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)};
const prettyDate=s=>fromISO(s).toLocaleDateString("es-MX",{weekday:"long",day:"numeric",month:"long",year:"numeric"});
const hourlyTimes=(start,end)=>Array.from({length:end-start+1},(_,index)=>`${pad(start+index)}:00`);
const timesForDate=date=>{const day=fromISO(date).getDay();if(day===1||day===5)return hourlyTimes(9,20);if(day===3)return["19:00","20:00"];if(day===2||day===4)return hourlyTimes(7,20);return[]};
const money=n=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0}).format(n);
const escapeHTML=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const phone=v=>String(v).replace(/\D/g,"");
const appointments=()=>{try{return JSON.parse(localStorage.getItem(CONFIG.storage))||[]}catch{return[]}};
let cloudBusy=[];
const save=list=>{const before=appointments(),beforeById=new Map(before.map(item=>[item.id,item])),afterIds=new Set(list.map(item=>item.id));localStorage.setItem(CONFIG.storage,JSON.stringify(list));list.forEach(item=>{const old=beforeById.get(item.id);if(!old||old.updatedAt!==item.updatedAt)window.CloudAppointments?.upsert(item).catch(()=>{})});before.forEach(item=>{if(!afterIds.has(item.id))window.CloudAppointments?.remove(item.id).catch(()=>{})})};
const service=id=>SERVICES.find(item=>item.id===id);
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
function showView(name){Object.values(views).forEach(v=>v.hidden=true);views[name].hidden=false;scrollTo({top:0,behavior:"smooth"})}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2500)}
function waLink(number,message){const digits=phone(number);const international=digits.length===10?`52${digits}`:digits;return `https://wa.me/${international}?text=${encodeURIComponent(message)}`}
function openWhatsApp(number,message){window.open(waLink(number,message),"_blank","noopener,noreferrer")}

function renderServices(){$("#serviceGrid").innerHTML=SERVICES.map(s=>`<button class="service-card${state.services.includes(s.id)?" selected":""}" data-service="${s.id}"><strong>${s.name}</strong><small>Servicio de fisioterapia</small><span class="service-meta"><span>60 min</span><span>${s.price?`Desde ${money(s.price)}`:"Precio por confirmar"}</span></span></button>`).join("");renderSelectedServices()}
function renderSelectedServices(){const selected=state.services.map(service).filter(Boolean),wrap=$("#selectedServices");wrap.hidden=!selected.length;$("#selectedServiceList").innerHTML=selected.map(s=>`<div class="selected-service-item"><div><strong>${escapeHTML(s.name)}</strong><span> · 60 min</span></div><button type="button" data-remove-service="${s.id}">Quitar</button></div>`).join("")}
function toggleService(id){state.services=state.services.includes(id)?[]:[id];state.date=null;state.time=null;renderServices();$("#dateStep").classList.toggle("is-locked",!state.services.length);$("#detailsStep").classList.add("is-locked");$("#timesWrap").hidden=true;renderCalendar();renderSummary();if(state.services.length)$("#dateStep").scrollIntoView({behavior:"smooth",block:"center"})}
function renderCalendar(){const cal=$("#calendar"),year=state.month.getFullYear(),month=state.month.getMonth(),today=new Date();today.setHours(0,0,0,0);$("#monthLabel").textContent=state.month.toLocaleDateString("es-MX",{month:"long",year:"numeric"});cal.innerHTML="";const first=new Date(year,month,1).getDay(),offset=first===0?6:first-1;for(let i=0;i<offset;i++)cal.append(document.createElement("span"));const total=new Date(year,month+1,0).getDate();for(let day=1;day<=total;day++){const date=new Date(year,month,day),iso=toISO(date),btn=document.createElement("button");btn.className=`day-btn${state.date===iso?" selected":""}`;btn.textContent=day;btn.disabled=date<today||!timesForDate(iso).length;if(!btn.disabled){btn.classList.add("available");btn.onclick=()=>selectDate(iso)}cal.append(btn)}}
function selectDate(iso){state.date=iso;state.time=null;renderCalendar();renderTimes();renderSummary()}
function availableTimes(date,ignoreId=""){const occupied=[...appointments().filter(a=>a.date===date&&a.id!==ignoreId).map(a=>a.time),...cloudBusy.filter(a=>a.date===date).map(a=>a.time)];return timesForDate(date).filter(t=>!occupied.includes(t))}
function renderTimes(){const wrap=$("#timesWrap"),grid=$("#timeGrid");wrap.hidden=false;$("#selectedDateLabel").textContent=`Horarios para ${prettyDate(state.date)}`;const times=availableTimes(state.date);grid.innerHTML=times.length?times.map(t=>`<button class="time-btn${state.time===t?" selected":""}" data-time="${t}">${t}</button>`).join(""):`<p class="time-empty">No quedan horarios disponibles ese día.</p>`}
function selectTime(time){state.time=time;renderTimes();$("#detailsStep").classList.remove("is-locked");renderSummary();$("#detailsStep").scrollIntoView({behavior:"smooth",block:"center"})}
function renderSummary(){const box=$("#liveSummary"),selected=state.services.map(service).filter(Boolean);if(!selected.length){box.className="empty-summary";box.textContent="Selecciona un servicio para comenzar.";return}const item=selected[0];box.className="";box.innerHTML=`<h4>${escapeHTML(item.name)}</h4><div class="summary-row"><span>Servicio</span><strong>${escapeHTML(item.name)}</strong></div><div class="summary-row"><span>Duración estimada</span><strong>60 min</strong></div><div class="summary-row"><span>Fecha</span><strong>${state.date?escapeHTML(prettyDate(state.date)):"Por elegir"}</strong></div><div class="summary-row"><span>Hora</span><strong>${state.time||"Por elegir"}</strong></div><div class="summary-row summary-total"><span>Precio</span><strong>${item.price?`Desde ${money(item.price)}`:"Por confirmar"}</strong></div>`}
function resetBooking(){Object.assign(state,{services:[],date:null,time:null,month:new Date(new Date().getFullYear(),new Date().getMonth(),1)});$("#bookingForm").reset();$("#dateStep").classList.add("is-locked");$("#detailsStep").classList.add("is-locked");$("#timesWrap").hidden=true;renderServices();renderCalendar();renderSummary()}
function confirmationMessage(a){const labels=(a.services||[{id:a.serviceId}]).map(entry=>service(entry.id)?.name).filter(Boolean).join(", ");return `¡Hola, ${a.name}!\n\nGracias por agendar en ${CONFIG.business}.\n\n📅 ${prettyDate(a.date)}\n🕐 ${a.time} h\n✨ ${labels}\n📍 ${CONFIG.address}\n${CONFIG.mapUrl?"🗺️ "+CONFIG.mapUrl+"\n":""}\nTe recordamos nuestras políticas:\n• Para cancelar o reagendar, avísanos con al menos 48 horas de anticipación.\n• Después de 10 minutos de retraso, la cita podrá cancelarse.\n• Una cita puede reagendarse un máximo de dos veces.\n\n¡Te esperamos!`}
function createAppointment(event){event.preventDefault();const name=$("#clientName").value.trim(),number=phone($("#clientPhone").value),accepted=$("#policyCheck").checked,error=$("#formError"),selected=state.services.map(service).filter(Boolean);if(!name||number.length<10||!accepted){error.textContent="Completa tu nombre, un WhatsApp válido y acepta las políticas.";return}if(!selected.length||!state.date||!state.time){error.textContent="Selecciona un servicio, fecha y hora.";return}if(!availableTimes(state.date).includes(state.time)){error.textContent="Ese horario acaba de ocuparse. Elige otro, por favor.";renderTimes();return}const services=selected.map(item=>({id:item.id,area:item.area})),first=services[0],now=new Date().toISOString(),item={id:uid(),name,phone:number,area:first.area,services,serviceId:first.id,date:state.date,time:state.time,price:selected.reduce((total,item)=>total+item.price,0),status:"Programada",reschedules:0,notes:$("#clientNotes").value.trim(),diagnosis:"",treatment:"",createdAt:now,updatedAt:now};const list=appointments();list.push(item);save(list);$("#confirmationSummary").innerHTML=`${selected.map(s=>`<div class="summary-row"><span>Servicio</span><strong>${escapeHTML(s.name)}</strong></div>`).join("")}<div class="summary-row"><span>Fecha</span><strong>${prettyDate(item.date)}</strong></div><div class="summary-row"><span>Hora</span><strong>${item.time} h</strong></div><div class="summary-row"><span>WhatsApp</span><strong>${escapeHTML(item.phone)}</strong></div><div class="summary-row location-summary"><span>Ubicación</span><strong>${escapeHTML(CONFIG.address)}${CONFIG.mapUrl?'<a class="confirmation-map-link" href="'+escapeHTML(CONFIG.mapUrl)+'" target="_blank" rel="noopener noreferrer">Abrir en Google Maps ↗</a>':""}</strong></div>`;showView("confirmation")}

function renderAdmin(){const date=$("#adminDate").value,list=appointments().filter(a=>a.date===date).sort((a,b)=>a.time.localeCompare(b.time));$("#appointmentList").innerHTML=list.length?list.map(a=>`<article class="appointment-item"><div class="appointment-time">${a.time} h</div><div><span class="status">Confirmada</span><h3>${escapeHTML(a.name)}</h3><p>${escapeHTML(service(a.serviceId)?.name||"Servicio")} · ${escapeHTML(a.phone)}</p>${a.notes?`<p>“${escapeHTML(a.notes)}”</p>`:""}</div><button class="secondary-btn" data-edit="${a.id}">Ver y editar</button></article>`).join(""):`<div class="empty-state">No hay citas registradas para este día.</div>`}
function fillEditTimes(selected,ignoreId){$("#editTime").innerHTML=availableTimes($("#editDate").value,ignoreId).concat(selected&&!availableTimes($("#editDate").value,ignoreId).includes(selected)?[selected]:[]).sort().map(t=>`<option value="${t}"${t===selected?" selected":""}>${t} h</option>`).join("")}
function openEdit(id){const a=appointments().find(x=>x.id===id);if(!a)return;$("#editId").value=a.id;$("#editName").value=a.name;$("#editPhone").value=a.phone;$("#editService").value=a.serviceId;$("#editDate").value=a.date;$("#editNotes").value=a.notes||"";fillEditTimes(a.time,a.id);$("#appointmentDialog").showModal()}
function saveEdit(e){e.preventDefault();const list=appointments(),index=list.findIndex(a=>a.id===$("#editId").value);if(index<0)return;list[index]={...list[index],name:$("#editName").value.trim(),phone:phone($("#editPhone").value),serviceId:$("#editService").value,date:$("#editDate").value,time:$("#editTime").value,notes:$("#editNotes").value.trim(),updatedAt:new Date().toISOString()};save(list);$("#appointmentDialog").close();$("#adminDate").value=list[index].date;renderAdmin();toast("Cita actualizada")}
function cancelAppointment(){const id=$("#editId").value;if(!confirm("¿Quieres cancelar y eliminar esta cita?"))return;save(appointments().filter(a=>a.id!==id));$("#appointmentDialog").close();renderAdmin();toast("Cita cancelada")}

$("#serviceGrid").addEventListener("click",e=>{const b=e.target.closest("[data-service]");if(b)toggleService(b.dataset.service)});$("#selectedServiceList").addEventListener("click",e=>{const b=e.target.closest("[data-remove-service]");if(b)toggleService(b.dataset.removeService)});$("#timeGrid").addEventListener("click",e=>{const b=e.target.closest("[data-time]");if(b)selectTime(b.dataset.time)});$("#bookingForm").addEventListener("submit",createAppointment);
function showPublicSite(){$("#publicHeader").hidden=false;document.querySelector("footer").hidden=false;showView("home")}
function prepareAgendaMarkup(root){
  root.querySelector(".quick-actions").innerHTML=`<button id="patientsBtn"><span>♙</span><div><strong>Pacientes</strong><small>Datos, diagnóstico, tratamiento y paquetes</small></div></button><button id="summaryBtn"><span>▦</span><div><strong>Ver resumen</strong><small>Consulta citas e ingresos</small></div></button><button id="paymentBtn"><span>↗</span><div><strong>Compartir información de pago</strong><small>Prepara el mensaje para el paciente</small></div></button><button id="policiesBtn"><span>i</span><div><strong>Ver políticas</strong><small>Consulta el texto de cada confirmación</small></div></button><button id="backupBtn"><span>↓</span><div><strong>Respaldo</strong><small>Descarga o recupera citas y pacientes</small></div></button>`;
  root.querySelector("#appointmentDialog").innerHTML=`<button class="dialog-close" data-close-dialog aria-label="Cerrar">×</button><p class="eyebrow" id="formEyebrow">Nueva cita</p><h2 id="formTitle">Agendar cita</h2><form id="appointmentForm" novalidate><input id="appointmentId" type="hidden"><label>Paciente registrado <span>(opcional)</span><select id="appointmentPatient"><option value="">Paciente nuevo</option></select></label><div class="package-banner" id="appointmentPackage" hidden></div><div class="form-row"><label>Nombre del paciente<input id="clientName" required autocomplete="name" placeholder="Nombre completo"></label><label>WhatsApp<input id="clientPhone" type="tel" required inputmode="tel" autocomplete="tel" placeholder="10 dígitos"></label></div><label class="check-row" id="savePatientLabel"><input id="savePatientCheck" type="checkbox" checked><span>Guardar paciente para próximas citas</span></label><div class="form-row"><label>Área<select id="areaSelect" required><option value="valuation">Valoración</option><option value="followup">Seguimiento</option><option value="valuation_treatment">Valoración y tratamiento</option><option value="revaluation">Revaloración</option></select></label><label>Servicio<select id="serviceSelect" required></select></label></div><div class="form-row"><label>Fecha<input id="appointmentDate" type="date" required></label><label>Hora<select id="appointmentTime" required></select></label></div><label>Precio acordado <span>(opcional)</span><input id="appointmentPrice" type="number" min="0" step="1" inputmode="decimal" placeholder="$0"></label><label>Diagnóstico <span>(opcional)</span><textarea id="appointmentDiagnosis" rows="3" placeholder="Diagnóstico o motivo clínico"></textarea></label><label>Tratamiento <span>(opcional)</span><textarea id="appointmentTreatment" rows="3" placeholder="Plan o tratamiento indicado"></textarea></label><label>Notas de la cita <span>(opcional)</span><textarea id="appointmentNotes" rows="3" placeholder="Indicaciones o detalles adicionales"></textarea></label><p class="form-error" id="formError"></p><div class="form-actions"><button class="danger-btn" id="deleteBtn" type="button" hidden>Cancelar cita</button><button class="primary-btn" type="submit">Guardar cita</button></div></form>`;
  root.querySelector("#summaryDialog").innerHTML=`<button class="dialog-close" data-close-dialog aria-label="Cerrar">×</button><p class="eyebrow">Actividad</p><h2>Resumen de la agenda</h2><div class="summary-tabs" role="group" aria-label="Periodo del resumen"><button type="button" class="active" data-summary-period="week">Esta semana</button><button type="button" data-summary-period="month">Este mes</button></div><p class="summary-range" id="summaryRange"></p><div class="summary-metrics"><article><small>Citas</small><strong id="summaryAppointments">0</strong></article><article><small>Ingresos</small><strong id="summaryIncome">$0</strong></article><article><small>Pacientes</small><strong id="summaryPatients">0</strong></article></div><div class="summary-list" id="summaryList"></div>`;
  root.querySelector("#backupDialog").innerHTML=`<button class="dialog-close" data-close-dialog aria-label="Cerrar">×</button><p class="eyebrow">Seguridad</p><h2>Respaldo</h2><p class="dialog-copy">Guarda una copia de las citas y los expedientes de pacientes.</p><div class="backup-count"><span>♡</span><div><strong id="backupAppointmentCount">0 citas y 0 pacientes</strong><small>Incluye diagnóstico, tratamiento y paquetes activos.</small></div></div><div class="backup-actions"><button type="button" class="primary-btn" id="exportBackupBtn">↓ Descargar respaldo</button><label class="backup-upload">↑ Restaurar respaldo<input id="importBackupInput" type="file" accept=".json,application/json"></label></div><p class="backup-note">Al restaurar, la información se combinará con la existente.</p><p class="form-error" id="backupError"></p>`;
  root.querySelector("#policiesDialog").innerHTML=`<button class="dialog-close" data-close-dialog aria-label="Cerrar">×</button><p class="eyebrow">Fisioterapia 5</p><h2>Políticas de citas</h2><p class="dialog-copy">Buscamos cuidar el tiempo de cada paciente y brindar el mejor servicio.</p><ul><li>Para cancelar o reagendar, avísanos con al menos 48 horas de anticipación.</li><li>Después de 10 minutos de retraso, la cita podrá cancelarse.</li><li>Una cita puede reagendarse un máximo de dos veces.</li></ul><button class="secondary-btn full" data-close-dialog>Entendido</button>`;
  const dialogs=document.createElement("div");dialogs.innerHTML=`<dialog id="patientsDialog" class="patients-dialog"><button class="dialog-close" data-close-dialog aria-label="Cerrar">×</button><p class="eyebrow">Expedientes</p><div class="dialog-title-row"><h2>Pacientes</h2><button class="secondary-btn" id="newPatientBtn" type="button">＋ Nuevo paciente</button></div><label>Buscar paciente<input id="patientSearch" type="search" placeholder="Nombre o WhatsApp"></label><div class="patient-list" id="patientList"></div></dialog><dialog id="patientEditorDialog"><button class="dialog-close" data-close-dialog aria-label="Cerrar">×</button><p class="eyebrow" id="patientFormEyebrow">Paciente</p><h2 id="patientFormTitle">Nuevo paciente</h2><form id="patientForm" novalidate><input id="patientId" type="hidden"><div class="form-row"><label>Nombre completo<input id="patientName" required autocomplete="name"></label><label>WhatsApp<input id="patientPhone" type="tel" required inputmode="tel"></label></div><label>Diagnóstico <span>(opcional)</span><textarea id="patientDiagnosis" rows="4" placeholder="Diagnóstico del paciente"></textarea></label><label>Tratamiento <span>(opcional)</span><textarea id="patientTreatment" rows="4" placeholder="Tratamiento o plan terapéutico"></textarea></label><fieldset class="package-fields"><legend>Paquete activo</legend><div class="form-row"><label>Paquete<select id="patientPackage"><option value="0">Sin paquete</option><option value="5">5 sesiones</option><option value="10">10 sesiones</option></select></label><label>Sesiones restantes<input id="patientSessions" type="number" min="0" max="10" step="1" value="0"></label></div></fieldset><p class="form-error" id="patientFormError"></p><div class="form-actions"><button class="danger-btn" id="deletePatientBtn" type="button" hidden>Eliminar paciente</button><button class="primary-btn" type="submit">Guardar paciente</button></div></form></dialog>`;[...dialogs.children].forEach(node=>root.append(node));
}
function loadAgenda(){const host=$("#agendaView");if(host.shadowRoot){window.refreshAgenda?.();return}const template=$("#agendaTemplate");template.innerHTML=template.innerHTML.replaceAll("agenda/css/styles.css","agenda/css/styles.css?v=fisio51").replaceAll("agenda/css/brand.css","agenda/css/brand.css?v=fisio51").replaceAll("agenda/css/summary.css","agenda/css/summary.css?v=fisio51");const root=host.attachShadow({mode:"open"});root.append(template.content.cloneNode(true));prepareAgendaMarkup(root);window.__agendaRoot=root;window.__agendaClose=showPublicSite;root.querySelectorAll(".embedded-back").forEach(button=>button.onclick=showPublicSite);const script=document.createElement("script");script.src="agenda/js/app.js?v=fisio52";document.head.append(script)}
function openSecureAgenda(){loadAgenda();$("#publicHeader").hidden=true;document.querySelector("footer").hidden=true;showView("agenda")}
$("#adminBtn").onclick=event=>{event.preventDefault();if(window.CloudAppointments?.isUnlocked()){openSecureAgenda();return}$("#adminAccessError").textContent="";$("#adminAccessForm").reset();$("#adminAccessDialog").showModal();setTimeout(()=>$("#adminAccessKey").focus(),50)};
$("#adminAccessForm").onsubmit=async event=>{event.preventDefault();const submit=event.submitter,error=$("#adminAccessError");error.textContent="";submit.disabled=true;submit.textContent="Comprobando…";try{await window.CloudAppointments?.unlock($("#adminAccessKey").value);$("#adminAccessDialog").close();openSecureAgenda()}catch{error.textContent="La clave de acceso no es correcta."}finally{submit.disabled=false;submit.textContent="Entrar a Mi agenda"}};
$("#startBookingBtn").onclick=()=>{resetBooking();showView("booking")};$$('[data-go-home]').forEach(b=>b.onclick=()=>showView("home"));
$("#prevMonth").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()-1,1);renderCalendar()};$("#nextMonth").onclick=()=>{state.month=new Date(state.month.getFullYear(),state.month.getMonth()+1,1);renderCalendar()};
$("#showPoliciesBtn").onclick=()=>$("#policiesDialog").showModal();$$('[data-close-dialog]').forEach(b=>b.onclick=()=>b.closest("dialog").close());const locationButton=$("#openLocationBtn");locationButton.hidden=!CONFIG.mapUrl;locationButton.onclick=()=>{if(CONFIG.mapUrl)window.open(CONFIG.mapUrl,"_blank","noopener,noreferrer")};
$("#todayBtn").onclick=()=>{$("#adminDate").value=toISO(new Date());renderAdmin()};$("#adminDate").onchange=renderAdmin;$("#appointmentList").onclick=e=>{const b=e.target.closest("[data-edit]");if(b)openEdit(b.dataset.edit)};$("#editDate").onchange=()=>fillEditTimes("",$("#editId").value);$("#editForm").onsubmit=saveEdit;$("#cancelAppointmentBtn").onclick=cancelAppointment;
$("#paymentBtn").onclick=()=>$("#paymentDialog").showModal();$("#paymentForm").onsubmit=e=>{e.preventDefault();const number=phone($("#paymentPhone").value);if(number.length<10){toast("Escribe un número válido");return}openWhatsApp(number,`Hola, buen día.\n\nTe compartimos la información de pago de ${CONFIG.business}:\n\n${CONFIG.bank}\n\nCuando realices tu transferencia, por favor envíanos tu comprobante. Gracias.`);$("#paymentDialog").close()};
$("#editService").innerHTML=SERVICES.map(s=>`<option value="${s.id}">${s.name}</option>`).join("");renderServices();renderCalendar();renderSummary();window.CloudAppointments?.hydrateAvailability(list=>{cloudBusy=list}).then(()=>{renderCalendar();renderSummary()});


